version: "3.8"
# 项目名
name: journey-project

services:
  # journey-client 服务
  journey-client:
    # 使用该镜像创建容器，镜像名称后面不加:latest标签，Docker 默认会使用latest标签的镜像
    image: journey-client:dev

    # 容器名称
    container_name: journey-client
    # 挂载的目录，主机：容器
    volumes:
      # 仅用于本地调试
      - /Users/lishuxue/Documents/study/journey/journey-client/dist:/journey-client/dist
    # 容器使用的网络
    networks:
      - journey-network
    # 自动重启，除非是手动停止了，否则容器内部错误都会自动重启
    restart: unless-stopped
    # 容器不存在时会先创建镜像，默认创建latest标签
    build:
      # 指定Dockerfile的构建上下文
      context: ./nginx-client
      dockerfile: Dockerfile.dev
      tags:
        - journey-client:dev

  journey-admin:
    image: journey-admin:dev
    container_name: journey-admin
    volumes:
      # 仅用于本地调试
      - /Users/lishuxue/Documents/study/journey/journey-admin/dist:/journey-admin/dist
    networks:
      - journey-network
    restart: unless-stopped
    build:
      context: ./nginx-admin
      dockerfile: Dockerfile.dev
      tags:
        - journey-admin:dev

  journey-nginx:
    image: journey-nginx:dev
    container_name: journey-nginx
    # 容器启动时映射的端口号，主机:容器
    ports:
      - 80:80
      - 443:443
    networks:
      - journey-network
    # 依赖其他的服务，需要依赖的服务先启动
    depends_on:
      - journey-client
      - journey-admin
    restart: unless-stopped
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile.dev
      tags:
        - journey-nginx:dev

  # 启动mongodb数据库，相当于使用下面docker命令
  # docker run -d --rm --name journey-mongodb -p 27017:27017 -v /root/mongodb/data/db:/data/db -v /root/project/journey/journey-mongodb:/data/configdb -v /root/mongodb/backup:/backup -e MONGO_INITDB_ROOT_USERNAME=lishuxue -e MONGO_INITDB_ROOT_PASSWORD=lishuxue --network journey-project_journey-network mongo --config /data/configdb/mongod.conf
  journey-mongodb:
    image: mongo:7.0.7-jammy
    container_name: journey-mongodb
    ports:
      - 27017:27017
    volumes:
      - /Users/lishuxue/Documents/software/mongodb/data/db:/data/db
      - /Users/lishuxue/Documents/study/journey/journey-docker/mongodb:/data/configdb
      - /Users/lishuxue/Documents/software/mongodb/backup:/backup # 用来备份
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lishuxue # 在admin数据库中创建新用户和密码
      - MONGO_INITDB_ROOT_PASSWORD=lishuxue
    command: mongod --config /data/configdb/mongod.conf # 用来指定容器启动时要执行的命令，可以覆盖默认命令
    networks:
      - journey-network
    restart: unless-stopped

  journey-server:
    image: journey-server:dev
    container_name: journey-server
    volumes:
      - /Users/lishuxue/Documents/study/journey/journey-server/logs:/journey-server/logs
      - /Users/lishuxue/Documents/study/journey/journey-server/dist:/journey-server/dist
    ports:
      - 4000:4000
    networks:
      - journey-network
    restart: unless-stopped
    depends_on:
      - journey-mongodb 
    build:
      context: ../journey-server
      dockerfile: Dockerfile.dev
      tags:
        - journey-server:dev

# 创建一个网络，down命令停止时会删除创建的网络
networks:
  journey-network:
    name: journey-network
    driver: bridge
# docker compose -f docker-compose.dev.yml up -d
# docker compose -f docker-compose.dev.yml down
