name: nginx-proxy # action名称

on: # 在push代码的时候运行此action
  push:
    branches:
      - main
      - master
    paths:
      - nginx-proxy/**

jobs:
  docker_build_deploy:
    runs-on: ubuntu-latest # 运行环境，最新ubuntu

    steps:
      - name: Checkout # check out the repository
        uses: actions/checkout@v4 # 这里使用了github官方提供的action,checkout项目到虚拟机上

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx-proxy
          push: true
          tags: lishuxue/journey-nginx:latest

      - name: docker stop # 停止服务
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: cd /root/project/journey/journey-docker && docker compose down journey-nginx
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: git pull # 服务器更新journey-docker代码
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: cd /root/project/journey/journey-docker && git pull
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: docker pull image # 服务器拉取最新镜像
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: docker pull lishuxue/journey-nginx
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: docker run # 启动服务
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: cd /root/project/journey/journey-docker && docker compose up -d journey-nginx
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: docker delete unused image # 删除多余的镜像
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: docker image prune --force
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
